# Generated by Django 4.2.6 on 2023-10-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_created=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("updated", models.DateField(auto_now=True)),
            ],
        ),
    ]
